import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="noise"></div>
      <section className="relative h-screen overflow-x-hidden">
        <h1 className="absolute left-8 top-8 font-hor text-6xl font-bold">
          NU dance club
        </h1>
        <div className="absolute left-80 top-32 ml-12 mt-12 text-lg text-gray-200">
          <div className="relative left-0 top-0 h-screen w-screen">
            <div className="absolute">
              <div className="group relative">
                <span className="absolute left-0 top-0 font-hor font-bold group-hover:text-white">
                  dancing
                </span>
                <span className="absolute left-10 top-10 w-[40rem]">
                  <Image
                    src="/images/1.webp"
                    width={500}
                    height={500}
                    alt="NU dance club"
                    className="max-h-[40rem] max-w-[40rem] shadow-2xl shadow-gray-400"
                  />
                </span>
              </div>
              <div className="group relative left-[calc(40rem)] top-24">
                <span className="absolute left-0 top-0 font-hor font-bold group-hover:text-white">
                  dancing
                </span>
                <span className="absolute left-10 top-10 w-[20rem]">
                  <Image
                    src="/images/10.webp"
                    width={500}
                    height={500}
                    alt="NU dance club"
                    className="shadow-2xl shadow-gray-400"
                  />
                </span>
              </div>
              <div className="group relative left-[calc(70rem)] top-24">
                <span className="absolute left-0 top-0 font-hor font-bold group-hover:text-white">
                  dancing
                </span>
                <span className="absolute left-10 top-10 w-[40rem]">
                  <Image
                    src="/images/9.webp"
                    width={500}
                    height={500}
                    alt="NU dance club"
                    className="shadow-2xl shadow-gray-400"
                  />
                </span>
              </div>
            </div>
          </div>
        </div>
        <div className="absolute bottom-8 left-8 text-xl font-medium text-gray-300">
          A way of creative life since 2018. All rights reserved.
        </div>
      </section>
      <section>
        <h2>About us</h2>
      </section>
    </>
  );
};

export default Home;
