import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="noise"></div>
      <section className="relative h-screen overflow-x-hidden">
        <div className="absolute left-8 top-8">
          <h1 className="font-hor text-4xl font-bold sm:text-6xl">
            NU dance club
          </h1>
          <p className="text-sm font-medium text-gray-300 sm:text-lg">
            A way of creative life since 2018. All rights reserved.
          </p>
        </div>
        <div className="absolute left-8 top-32 ml-12 mt-12 text-sm text-gray-200 sm:left-80 sm:top-20 sm:text-lg">
          <div className="relative left-0 top-0 h-screen w-screen">
            <div className="absolute">
              <div className="group relative -left-[2rem] top-[0rem] sm:top-20">
                <span className="absolute left-0 top-0 font-hor font-bold group-hover:text-white">
                  practicing
                </span>
                <span className="absolute left-6 top-6 w-[12rem] sm:left-10 sm:top-10 sm:w-[40rem]">
                  <Image
                    src="/images/1.webp"
                    width={500}
                    height={500}
                    alt="NU dance club"
                    className="shadow-2xl shadow-gray-400"
                  />
                </span>
              </div>
              <div className="group relative left-20 top-[9rem] sm:left-[calc(36rem)] sm:top-[12rem]">
                <span className="absolute left-32 top-0 font-hor font-bold group-hover:text-white sm:left-0">
                  partying
                </span>
                <span className="absolute left-6 top-6 w-[12rem] sm:left-10 sm:top-10 sm:w-[20rem]">
                  <Image
                    src="/images/10.webp"
                    width={500}
                    height={500}
                    alt="NU dance club"
                    className="shadow-2xl shadow-gray-400"
                  />
                </span>
              </div>
              <div className="group relative -left-8 top-[28rem] sm:left-[calc(64rem)] sm:top-8">
                {/* <div className="group relative left-20 top-[9rem] sm:left-[calc(36rem)] sm:top-[12rem]"> */}
                <span className="absolute left-0 top-0 font-hor font-bold group-hover:text-white">
                  dancing
                </span>
                <span className="absolute left-6 top-6 w-[12rem] sm:left-10 sm:top-10 sm:w-[40rem]">
                  <Image
                    src="/images/9.webp"
                    width={500}
                    height={500}
                    alt="NU dance club"
                    className="shadow-2xl shadow-gray-400"
                  />
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section>
        <h2>About us</h2>
      </section>
    </>
  );
};

export default Home;
